services:
  web:
    container_name: web
    image: gowtham/auth:latest
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres-db
    ports:
      - "8080:8080"
    depends_on:
      - psql_bp
  psql_bp:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${BLUEPRINT_DB_DATABASE}
      POSTGRES_USER: ${BLUEPRINT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

volumes:
  psql_volume_bp:
